#! /bin/bash

while read line; do
find -name "*.java" -exec perl -p -i -e "${line}" {} \;
done <<EOF
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.statement/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.statement/g
s/\\\Qorg.iglooproject.wicket.more.WicketBootstrapPackage/org.iglooproject.wicket.bootstrap3.WicketBootstrapPackage/g
s/\\\Qorg.iglooproject.wicket.more.application.WicketBootstrapModule/org.iglooproject.wicket.bootstrap3.application.WicketBootstrapModule/g
s/\\\Qorg.iglooproject.wicket.more.config.spring.WicketBootstrapServiceConfig/org.iglooproject.wicket.bootstrap3.config.spring.WicketBootstrapServiceConfig/g
s/\\\Qorg.iglooproject.wicket.more.config.spring.AbstractBootstrapWebappConfig/org.iglooproject.wicket.bootstrap3.config.spring.AbstractBootstrapWebappConfig/g
s/\\\Qorg.iglooproject.wicket.more.console.navigation.page.ConsoleSignInPage/org.iglooproject.wicket.bootstrap3.console.navigation.page.ConsoleSignInPage/g
s/\\\Qorg.iglooproject.wicket.more.console.navigation.page.ConsoleAccessDeniedPage/org.iglooproject.wicket.bootstrap3.console.navigation.page.ConsoleAccessDeniedPage/g
s/\\\Qorg.iglooproject.wicket.more.console.navigation.page.ConsoleLoginFailurePage/org.iglooproject.wicket.bootstrap3.console.navigation.page.ConsoleLoginFailurePage/g
s/\\\Qorg.iglooproject.wicket.more.console.navigation.page.ConsoleLoginSuccessPage/org.iglooproject.wicket.bootstrap3.console.navigation.page.ConsoleLoginSuccessPage/g
s/\\\Qorg.iglooproject.wicket.more.console.resources.CoreWicketConsoleResources/org.iglooproject.wicket.bootstrap3.console.resources.CoreWicketConsoleResources/g
s/\\\Qorg.iglooproject.wicket.more.console.common.util.LinkUtils/org.iglooproject.wicket.bootstrap3.console.common.util.LinkUtils/g
s/\\\Qorg.iglooproject.wicket.more.console.common.component.JavaClassesListMultipleChoice/org.iglooproject.wicket.bootstrap3.console.common.component.JavaClassesListMultipleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.common.component.PropertyIdListPanel/org.iglooproject.wicket.bootstrap3.console.common.component.PropertyIdListPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.common.form.PropertyIdEditPopup/org.iglooproject.wicket.bootstrap3.console.common.form.PropertyIdEditPopup/g
s/\\\Qorg.iglooproject.wicket.more.console.template.ConsoleTemplate/org.iglooproject.wicket.bootstrap3.console.template.ConsoleTemplate/g
s/\\\Qorg.iglooproject.wicket.more.console.template.ConsoleConfiguration/org.iglooproject.wicket.bootstrap3.console.template.ConsoleConfiguration/g
s/\\\Qorg.iglooproject.wicket.more.console.template.style.ConsoleLessCssResourceReference/org.iglooproject.wicket.bootstrap3.console.template.style.ConsoleLessCssResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.console.template.style.ConsoleSignInLessCssResourceReference/org.iglooproject.wicket.bootstrap3.console.template.style.ConsoleSignInLessCssResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.console.template.style.CoreConsoleCssScope/org.iglooproject.wicket.bootstrap3.console.template.style.CoreConsoleCssScope/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.ehcache.page.ConsoleMaintenanceEhCachePage/org.iglooproject.wicket.bootstrap3.console.maintenance.ehcache.page.ConsoleMaintenanceEhCachePage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.ehcache.component.EhCacheProgressBarComponent/org.iglooproject.wicket.bootstrap3.console.maintenance.ehcache.component.EhCacheProgressBarComponent/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.ehcache.component.EhCacheCachePortfolioPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.ehcache.component.EhCacheCachePortfolioPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.ehcache.component.EhCacheCacheModificationPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.ehcache.component.EhCacheCacheModificationPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.file.page.ConsoleMaintenanceFilePage/org.iglooproject.wicket.bootstrap3.console.maintenance.file.page.ConsoleMaintenanceFilePage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.search.page.ConsoleMaintenanceSearchPage/org.iglooproject.wicket.bootstrap3.console.maintenance.search.page.ConsoleMaintenanceSearchPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.queuemanager.renderer.QueueTaskRenderer/org.iglooproject.wicket.bootstrap3.console.maintenance.queuemanager.renderer.QueueTaskRenderer/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.queuemanager.renderer.QueueManagerRenderer/org.iglooproject.wicket.bootstrap3.console.maintenance.queuemanager.renderer.QueueManagerRenderer/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.queuemanager.page.ConsoleMaintenanceQueueManagerPage/org.iglooproject.wicket.bootstrap3.console.maintenance.queuemanager.page.ConsoleMaintenanceQueueManagerPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.queuemanager.component.ConsoleMaintenanceQueueManagerNodePanel/org.iglooproject.wicket.bootstrap3.console.maintenance.queuemanager.component.ConsoleMaintenanceQueueManagerNodePanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.authentication.page.ConsoleMaintenanceAuthenticationPage/org.iglooproject.wicket.bootstrap3.console.maintenance.authentication.page.ConsoleMaintenanceAuthenticationPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.renderer.INodeRenderer/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.renderer.INodeRenderer/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.page.ConsoleMaintenanceInfinispanPage/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.page.ConsoleMaintenanceInfinispanPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanNodesPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanNodesPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanLocksPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanLocksPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanRolesPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanRolesPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanRolesRequestsPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanRolesRequestsPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanClusterPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.component.ConsoleMaintenanceInfinispanClusterPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.form.NodeDropDownSingleChoice/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.form.NodeDropDownSingleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.infinispan.form.ConsoleMaintenanceInfinispanRoleAssignPopup/org.iglooproject.wicket.bootstrap3.console.maintenance.infinispan.form.ConsoleMaintenanceInfinispanRoleAssignPopup/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.page.ConsoleMaintenanceTaskDescriptionPage/org.iglooproject.wicket.bootstrap3.console.maintenance.task.page.ConsoleMaintenanceTaskDescriptionPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.page.ConsoleMaintenanceTaskListPage/org.iglooproject.wicket.bootstrap3.console.maintenance.task.page.ConsoleMaintenanceTaskListPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskTypeListMultipleChoice/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskTypeListMultipleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskQueueIdListMultipleChoice/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskQueueIdListMultipleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskStatusPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskStatusPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskExecutionResultPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskExecutionResultPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskResultListMultipleChoice/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskResultListMultipleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskFilterPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskFilterPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskStatusListMultipleChoice/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskStatusListMultipleChoice/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskManagerInformationPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskManagerInformationPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskResultPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskResultPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.task.component.TaskResultsPanel/org.iglooproject.wicket.bootstrap3.console.maintenance.task.component.TaskResultsPanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.gestion.page.ConsoleMaintenanceGestionPage/org.iglooproject.wicket.bootstrap3.console.maintenance.gestion.page.ConsoleMaintenanceGestionPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.upgrade.page.ConsoleMaintenanceDonneesPage/org.iglooproject.wicket.bootstrap3.console.maintenance.upgrade.page.ConsoleMaintenanceDonneesPage/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.upgrade.component.DataUpgradePanel/org.iglooproject.wicket.bootstrap3.console.maintenance.upgrade.component.DataUpgradePanel/g
s/\\\Qorg.iglooproject.wicket.more.console.maintenance.template.ConsoleMaintenanceTemplate/org.iglooproject.wicket.bootstrap3.console.maintenance.template.ConsoleMaintenanceTemplate/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.bootstrap.WicketBootstrapComponentsModule/org.iglooproject.wicket.bootstrap3.markup.html.bootstrap.WicketBootstrapComponentsModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.bootstrap.component.BootstrapLabel/org.iglooproject.wicket.bootstrap3.markup.html.bootstrap.component.BootstrapLabel/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.bootstrap.component.BootstrapBadge/org.iglooproject.wicket.bootstrap3.markup.html.bootstrap.component.BootstrapBadge/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.collapse.BootstrapCollapseJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.collapse.BootstrapCollapseJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.dropdown.BootstrapDropdownModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.dropdown.BootstrapDropdownModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.dropdown.BootstrapDropDownJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.dropdown.BootstrapDropDownJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.confirm.BootstrapConfirmModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.confirm.BootstrapConfirmModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.confirm.BootstrapConfirmJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.confirm.BootstrapConfirmJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.tooltip.BootstrapTooltipModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.tooltip.BootstrapTooltipModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.tooltip.BootstrapTooltipJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.tooltip.BootstrapTooltipJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.popover.BootstrapPopoverJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.popover.BootstrapPopoverJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.popover.BootstrapPopoverModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.popover.BootstrapPopoverModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.alert.BootstrapAlertJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.alert.BootstrapAlertJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.SimpleOptions/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.SimpleOptions/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.affix.BootstrapAffixOptions/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.affix.BootstrapAffixOptions/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.affix.BootstrapAffixBehavior/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.affix.BootstrapAffixBehavior/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.affix.BootstrapAffixJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.affix.BootstrapAffixJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.tab.BootstrapTabModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.tab.BootstrapTabModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.tab.BootstrapTabJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.tab.BootstrapTabJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.BootstrapModalJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.BootstrapModalJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.BootstrapModalModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.BootstrapModalModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.statement.BootstrapModalManager/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.statement.BootstrapModalManager/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.statement.BootstrapModalManagerStatement/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.statement.BootstrapModalManagerStatement/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.modal.BootstrapModalManagerJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.modal.BootstrapModalManagerJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.button.BootstrapButtonJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.button.BootstrapButtonJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.button.BootstrapButtonModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.button.BootstrapButtonModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.scrollspy.BootstrapScrollSpyJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.scrollspy.BootstrapScrollSpyJavaScriptResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.bootstrap.scrollspy.BootstrapScrollSpyModule/org.iglooproject.wicket.bootstrap3.markup.html.template.js.bootstrap.scrollspy.BootstrapScrollSpyModule/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.css.select2.Select2CssResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.css.select2.Select2CssResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.css.bootstrap.fontawesome.CoreFontAwesomeCssScope/org.iglooproject.wicket.bootstrap3.markup.html.template.css.bootstrap.fontawesome.CoreFontAwesome4CssScope/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.css.bootstrap.CoreBootstrap3CssScope/org.iglooproject.wicket.bootstrap3.markup.html.template.css.bootstrap.CoreBootstrap3CssScope/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.css.bootstrap.bootstrap.DefaultBootstrap3LessCssResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.css.bootstrap.bootstrap.DefaultBootstrap3LessCssResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.css.bootstrap.jqueryui.JQueryUiCssResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.css.bootstrap.jqueryui.JQueryUiCssResourceReference/g
s/\\\Qorg.iglooproject.wicket.more.markup.html.template.js.respond.RespondJavaScriptResourceReference/org.iglooproject.wicket.bootstrap3.markup.html.template.js.respond.RespondJavaScriptResourceReference/g
EOF
